### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by Projectmaster122**
(made with mitko) pls dont hate

### CODE REVIEW

**Comment by usarana** [comment]
i approve of this

**Comment by Projectmaster122** [comment]
why

**Comment by Projectmaster122** [comment]
its minor QA

**Comment by tizu69** [comment]
image

make it less obvious next time

**Comment by Projectmaster122** [comment]
bro it aint that much

**Comment by Projectmaster122** [comment]
e

**Comment by usarana** [comment]
As a person identifying as a deez chord, I can relate to mr. Projectmaster122

**Comment by Projectmaster122** [comment]
PLS NO

**Comment by usarana** [comment]
mr. Projectmaster122 declares protest

**Comment by tizu69** [comment]
this is the worst joke I've ever seen

**Pull request closed without merging**
